<?php
include "../../include/conn.php";
include "fungsi.php";
ini_set('date.timezone', 'Asia/Jakarta');
session_start();

$no_memo = $_REQUEST['no_memo'];
$user = $_SESSION['username'];
$app_date = date("Y-m-d H:i:s");
$sql = "update memo_h set status='APPROVED',approved_by='$user',approved_date = '$app_date' where nm_memo = '$no_memo'";
$query = mysqli_query($conn_li,$sql);

$sql_jurnal = "insert into tbl_list_journal 
(select '' id,nm_memo,tgl_memo,'MEMO-EXIM' type_journal,no_coa,nama_coa,id_cc,cc_name,inv_vendor no_reff,'' reff_date,buyer,'-' no_ws, curr,IF(curr = 'IDR',1,COALESCE(rate,1)) rate,'0' debit, total credit, '0' debit_idr, (total * IF(curr = 'IDR',1,COALESCE(rate,1))) credit_idr, 'APPROVED' status, keterangan, user,date_input,'$user' app_by, '$app_date' app_date, '' cancel_by, '' cancel_date,'','','' from (select *,sum(biaya) total from (select a.id_h,a.nm_memo,a.tgl_memo,map.no_coa_cre no_coa,map.nama_coa_cre nama_coa,map.id_cc,map.cc_name,mb.supplier buyer,a.curr,mdet.biaya biaya,UPPER(CONCAT('HANDLING ',a.jns_trans,' (',ms.supplier, '), BUYER ',mb.supplier,', ',inv_vendor)) keterangan,a.user,a.date_input ,map.status,mdet.inv_vendor from memo_h a inner join mastersupplier ms on a.id_supplier = ms.id_supplier inner join mastersupplier mb on a.id_buyer = mb.id_supplier inner join memo_det mdet on mdet.id_h = a.id_h left join master_memo_item it on it.id = a.id_item left join memo_mapping_v2 map on map.id_ctg = mdet.id_ctg and map.id_sub_ctg = mdet.id_sub_ctg and map.jns_trans = a.jns_trans and map.ditagihkan = a.ditagihkan and map.id_item = a.id_item or map.id_ctg = mdet.id_ctg and map.id_sub_ctg = mdet.id_sub_ctg and map.jns_trans = a.jns_trans and map.ditagihkan = a.ditagihkan where mdet.cancel = 'N' and map.status = 'Y' and mdet.nm_sub_ctg != 'VAT' and a.nm_memo = '$no_memo' GROUP BY mdet.id order by mdet.id) a left join (select tanggal,rate from masterrate where v_codecurr = 'PAJAK') b on b.tanggal = a.tgl_memo GROUP BY a.inv_vendor) a) 
UNION 
(select '' id,nm_memo,tgl_memo,'MEMO-EXIM' type_journal,no_coa,nama_coa,id_cc,cc_name,inv_vendor no_reff,'' reff_date,buyer,'-' no_ws, curr,IF(curr = 'IDR',1,COALESCE(rate,1)) rate,'0' debit, total credit, '0' debit_idr, (total * IF(curr = 'IDR',1,COALESCE(rate,1))) credit_idr, 'APPROVED' status, keterangan, user,date_input,'$user' app_by, '$app_date' app_date, '' cancel_by, '' cancel_date,'','','' from (select *,sum(biaya) total from (select a.id_h,a.nm_memo,a.tgl_memo,map.no_coa_cre no_coa,map.nama_coa_cre nama_coa,map.id_cc,map.cc_name,mb.supplier buyer,a.curr,mdet.biaya biaya,UPPER(CONCAT('HANDLING ',a.jns_trans,' (',ms.supplier, '), BUYER ',mb.supplier,', ',inv_vendor)) keterangan,a.user,a.date_input ,map.status,mdet.inv_vendor from memo_h a inner join mastersupplier ms on a.id_supplier = ms.id_supplier inner join mastersupplier mb on a.id_buyer = mb.id_supplier inner join memo_det mdet on mdet.id_h = a.id_h left join master_memo_item it on it.id = a.id_item left join memo_mapping_v2 map on map.id_ctg = mdet.id_ctg and map.id_sub_ctg = mdet.id_sub_ctg and map.jns_trans = a.jns_trans and map.ditagihkan = a.ditagihkan and map.id_item = a.id_item or map.id_ctg = mdet.id_ctg and map.id_sub_ctg = mdet.id_sub_ctg and map.jns_trans = a.jns_trans and map.ditagihkan = a.ditagihkan where mdet.cancel = 'N' and map.status = 'Y' and mdet.nm_sub_ctg = 'VAT' and a.nm_memo = '$no_memo' GROUP BY mdet.id order by mdet.id) a left join (select tanggal,rate from masterrate where v_codecurr = 'PAJAK') b on b.tanggal = a.tgl_memo GROUP BY a.inv_vendor) a) 
UNION 
(select '' id,nm_memo,tgl_memo,'MEMO-EXIM' type_journal,no_coa,nama_coa,id_cc,cc_name,inv_vendor no_reff,'' reff_date,buyer,'-' no_ws, curr,IF(curr = 'IDR',1,COALESCE(rate,1)) rate,biaya debit, '0' credit, (biaya * IF(curr = 'IDR',1,COALESCE(rate,1))) debit_idr, '0' credit_idr, 'APPROVED' status, keterangan, user,date_input,'$user' app_by, '$app_date' app_date, '' cancel_by, '' cancel_date,'','','' from (select * from (select a.id_h,a.nm_memo,a.tgl_memo,map.no_coa,map.nama_coa,map.id_cc,map.cc_name,mb.supplier buyer,a.curr,mdet.biaya,UPPER(CONCAT(mdet.nm_sub_ctg,' (',ms.supplier, '), BUYER ',mb.supplier, ', ',a.jns_trans, ', ',inv_vendor)) keterangan,a.user,a.date_input ,map.status,mdet.inv_vendor from memo_h a inner join mastersupplier ms on a.id_supplier = ms.id_supplier inner join mastersupplier mb on a.id_buyer = mb.id_supplier inner join memo_det mdet on mdet.id_h = a.id_h left join master_memo_item it on it.id = a.id_item left join memo_mapping_v2 map on map.id_ctg = mdet.id_ctg and map.id_sub_ctg = mdet.id_sub_ctg and map.jns_trans = a.jns_trans and map.ditagihkan = a.ditagihkan and map.id_item = a.id_item or map.id_ctg = mdet.id_ctg and map.id_sub_ctg = mdet.id_sub_ctg and map.jns_trans = a.jns_trans and map.ditagihkan = a.ditagihkan where mdet.cancel = 'N' and map.status = 'Y' and a.nm_memo = '$no_memo' GROUP BY mdet.id order by mdet.id_h) a left join (select tanggal,rate from masterrate where v_codecurr = 'PAJAK') b on b.tanggal = a.tgl_memo) a)";
$query_jurnal = mysqli_query($conn_li,$sql_jurnal);

?>
